spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eorganization_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
      continue-on-error: true

jwt:
  secret: "p0hAmehHGcRVNNUTmlK8RT7nHfwAKzzHxMicPlZHuFU="
  accessTokenValiditySeconds: 3600     # 1 hour
  refreshTokenValiditySeconds: 1209600 # 14 days

server:
  port: 8080
